image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - lib/

test:
  stage: test
  script: npm test
